import plan1 from '../assets/S1.png';
import plan2 from '../assets/S2.png';
import plan3 from '../assets/S3.png';
import plan4 from '../assets/S4.png';
export const stanoviConstants = {
  floors: [
    {
      floor_number: 1,
      apartments: [
        {
          number: 1,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 1,
          sobnost: 'Jednosoban',
          plan_image: plan1,
        },
        {
          number: 2,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 2,
          sobnost: 'Dvosoban',
        },
        {
          number: 3,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 3,
          sobnost: 'Dvosoban',
        },
        {
          number: 4,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 4,
          sobnost: 'Trosoban',
        },
      ],
    },
    {
      floor_number: 2,
      apartments: [
        {
          number: 5,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 1,
          sobnost: 'Jednosoban',
          plan_image: plan1,
        },
        {
          number: 6,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 2,
          sobnost: 'Dvosoban',
        },
        {
          number: 7,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 3,
          sobnost: 'Dvosoban',
        },
        {
          number: 8,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 4,
          sobnost: 'Trosoban',
        },
      ],
    },
    {
      floor_number: 3,
      apartments: [
        {
          number: 9,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 1,
          sobnost: 'Jednosoban',
          plan_image: plan1,
        },
        {
          number: 10,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 2,
          sobnost: 'Dvosoban',
        },
        {
          number: 11,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 3,
          sobnost: 'Dvosoban',
        },
        {
          number: 12,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 4,
          sobnost: 'Trosoban',
        },
      ],
    },
    {
      floor_number: 4,
      apartments: [
        {
          number: 13,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 1,
          sobnost: 'Jednosoban',
          plan_image: plan1,
        },
        {
          number: 14,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 2,
          sobnost: 'Dvosoban',
        },
        {
          number: 15,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 3,
          sobnost: 'Dvosoban',
        },
        {
          number: 16,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 4,
          sobnost: 'Trosoban',
        },
      ],
    },
  ],
};
