import plan1 from '../assets/S1.png';
import plan2 from '../assets/S2.png';
import plan3 from '../assets/S3.png';
import plan4 from '../assets/S4.png';
import plan17 from '../assets/s17.jpeg';
import plan18 from '../assets/s18.jpeg';
import tlocrt1 from '../assets/tlocrti/t1.jpeg';
import tlocrt2 from '../assets/tlocrti/t2.jpeg';
import tlocrt3 from '../assets/tlocrti/t3.jpeg';
import tlocrt4 from '../assets/tlocrti/t4.jpeg';
import tlocrt5 from '../assets/tlocrti/t5.jpeg';
import tlocrt6 from '../assets/tlocrti/t6.jpeg';
import tlocrt7 from '../assets/tlocrti/t7.jpeg';
import tlocrt8 from '../assets/tlocrti/t8.jpeg';
import tlocrt9 from '../assets/tlocrti/t9.jpeg';
import tlocrt10 from '../assets/tlocrti/t10.jpeg';
import tlocrt11 from '../assets/tlocrti/t11.jpeg';
import tlocrt12 from '../assets/tlocrti/t12.jpeg';
import tlocrt13 from '../assets/tlocrti/t13.jpeg';
import tlocrt14 from '../assets/tlocrti/t14.jpeg';
import tlocrt15 from '../assets/tlocrti/t15.jpeg';
import tlocrt16 from '../assets/tlocrti/t16.jpeg';
import tlocrt17 from '../assets/tlocrti/t17.jpeg';
import tlocrt18 from '../assets/tlocrti/t18.jpeg';

export const stanoviConstants = {
  floors: [
    {
      floor_number: 1,
      apartments: [
        {
          number: 1,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 'S1',
          sobnost: 'Jednosoban',
          plan_image: plan1,
          tlocrt: tlocrt1,
        },
        {
          number: 2,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 'S2',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt2,
        },
        {
          number: 3,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 'S3',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt3,
        },
        {
          number: 4,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 'S4',
          sobnost: 'Trosoban',
          tlocrt: tlocrt4,
        },
      ],
    },
    {
      floor_number: 2,
      apartments: [
        {
          number: 5,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 'S5',
          sobnost: 'Jednosoban',
          plan_image: plan1,
          tlocrt: tlocrt5,
        },
        {
          number: 6,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 'S6',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt6,
        },
        {
          number: 7,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 'S7',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt7,
        },
        {
          number: 8,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 'S8',
          sobnost: 'Trosoban',
          tlocrt: tlocrt8,
        },
      ],
    },
    {
      floor_number: 3,
      apartments: [
        {
          number: 9,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 'S9',
          sobnost: 'Jednosoban',
          plan_image: plan1,
          tlocrt: tlocrt9,
        },
        {
          number: 10,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 'S10',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt10,
        },
        {
          number: 11,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 'S11',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt11,
        },
        {
          number: 12,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 'S12',
          sobnost: 'Trosoban',
          tlocrt: tlocrt12,
        },
      ],
    },
    {
      floor_number: 4,
      apartments: [
        {
          number: 13,
          area_sqm: 45.31,
          bedrooms: 1,
          bathrooms: 1,
          livingroom_size: 26.54,
          bedrooms_size: 11.39,
          bathrooms_size: 3.97,
          loggia_size: 4.54,
          tip: 'S13',
          sobnost: 'Jednosoban',
          plan_image: plan1,
          tlocrt: tlocrt13,
        },
        {
          number: 14,
          area_sqm: 81.67,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 36.43,
          pantry_size: 1.85,
          laundryroom_size: 1.78,
          hall_size: 7.15,
          bedrooms_size: 10.82,
          bedrooms_size2: 12.41,
          wc_size: 1.73,
          bathrooms_size: 3.71,
          loggia_size: 7.72,
          plan_image: plan2,
          tip: 'S14',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt14,
        },
        {
          number: 15,
          area_sqm: 78.11,
          bedrooms: 2,
          bathrooms: 2,
          livingroom_size: 33.41,
          laundryroom_size: 2.07,
          hall_size: 9.31,
          bedrooms_size: 11.8,
          bedrooms_size2: 11.38,
          wc_size: 1.73,
          bathrooms_size: 3.37,
          loggia_size: 6.72,
          plan_image: plan3,
          tip: 'S15',
          sobnost: 'Dvosoban',
          tlocrt: tlocrt15,
        },
        {
          number: 16,
          area_sqm: 95.93,
          bedrooms: 3,
          bathrooms: 2,
          livingroom_size: 34.88,
          laundryroom_size: 2.07,
          hall_size: 11.19,
          bedrooms_size: 11.95,
          bedrooms_size2: 9.12,
          bedrooms_size3: 12.46,
          bathrooms_size: 4.18,
          wc_size: 1.73,
          loggia_size: 11.8,
          plan_image: plan4,
          tip: 'S16',
          sobnost: 'Trosoban',
          tlocrt: tlocrt16,
        },
      ],
    },
    {
      floor_number: 5,
      apartments: [
        {
          number: 17,
          area_sqm: 163.83,
          bedrooms: 3,
          bathrooms: 3,
          livingroom_size: 56.26,
          pantry_size: 2.97,
          wc_size: 1.97,
          hall_size: 19.95,
          bathrooms_size: 5.49,
          bathrooms_size2: 4.17,
          laundryroom_size: 4.22,
          bedrooms_size: 18.43,
          bedrooms_size2: 10.88,
          bedrooms_size3: 12.51,
          loggia_size: 26.88,
          tip: 'S17',
          sobnost: 'Trosoban',
          plan_image: plan17,
          tlocrt: tlocrt17,
        },
        {
          number: 18,
          area_sqm: 126.97,
          bedrooms: 3,
          bathrooms: 3,
          livingroom_size: 39.1,
          pantry_size: 3.73,
          wc_size: 2.04,
          hall_size: 13.41,
          bathrooms_size: 5.69,
          bathrooms_size2: 3.49,
          laundryroom_size: 3.68,
          bedrooms_size: 16.93,
          bedrooms_size2: 13.02,
          bedrooms_size3: 16.18,
          terrace_size: 9.7,
          tip: 'S18',
          sobnost: 'Trosoban',
          plan_image: plan18,
          tlocrt: tlocrt18,
        },
      ],
    },
  ],
};
